// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgmacqnypvrlkqiucdig.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnbWFjcW55cHZybGtxaXVjZGlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc5MzAzMDEsImV4cCI6MjA5MzUwNjMwMX0.P9MiSS8_NBq9KpBUyKrr33k3VfiDPJ9tmmkKx27wtLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});